apiVersion: v2
name: todo-chatbot
description: A Helm chart for deploying Todo Chatbot application with frontend and backend
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - todo
  - chatbot
  - kubernetes
maintainers:
  - name: Todo Chatbot Team
